fos_elastica:
    indexes:
        majesteel_back:
            client: default
            finder: ~
            types:
                user:
                    mappings:
                        username: { analyzer: snowball }
                        email: { analyzer: snowball }
                        firstname: { analyzer: snowball }
                        lastname: { analyzer: snowball }
                        tags: { analyzer: letter }
                    persistence:
                        driver: orm
                        model: Majes\CoreBundle\Entity\User\User
                        provider: ~
                        finder: ~
                        listener:
                            insert: true
                            update: true
                            delete: true
                role:
                    mappings:
                        name: { analyzer: snowball }
                        role: { analyzer: snowball }
                        tags: { analyzer: letter }
                    persistence:
                        driver: orm
                        model: Majes\CoreBundle\Entity\User\Role
                        provider: ~
                        finder: ~
                        listener:
                            insert: true
                            update: true
                            delete: true
                page:
                    mappings:
                        content: { analyzer: snowball }
                        metaDescription: { analyzer: snowball }
                        title: { analyzer: snowball }
                        url: { analyzer: snowball }
                        tags: { analyzer: letter }
                    persistence:
                        driver: orm
                        model: Majes\CmsBundle\Entity\PageLang
                        provider:
                            query_builder_method: createIsActiveQueryBuilder
                        finder: ~
                        listener:
                            insert: true
                            update: true
                            delete: true
                            is_indexable_callback: "isIndexable"
        majesteel_front:
            client: default
            finder: ~
            types:
                page:
                    mappings:
                        content: { analyzer: snowball }
                        metaDescription: { analyzer: snowball }
                        title: { analyzer: snowball }
                        url: { analyzer: snowball }
                        locale: { analyzer: keyword }
                        tags: { analyzer: letter }
                    persistence:
                        driver: orm
                        model: Majes\CmsBundle\Entity\PageLang
                        provider:
                            query_builder_method: createIsActiveQueryBuilder
                        finder: ~
                        listener:
                            insert: true
                            update: true
                            delete: true
                            is_indexable_callback: "isIndexable"
